kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
  namespace: nginx
  labels:
    purpose: development
    app: local

spec:
  accessModes:                               # gives access to read write atleast once
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage            # storage on local machine
